// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWwof31d1b1qOXlIBDCjX7ETratJsN82Y',
    appId: '1:1033223278662:web:61048dfcecc9b00b62ba47',
    messagingSenderId: '1033223278662',
    projectId: 'chatapp-9da17',
    authDomain: 'chatapp-9da17.firebaseapp.com',
    storageBucket: 'chatapp-9da17.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMO0RUi27uvyCQ0OnS_vfibbLvPr2xvY8',
    appId: '1:1033223278662:android:cbd5e730d119235262ba47',
    messagingSenderId: '1033223278662',
    projectId: 'chatapp-9da17',
    storageBucket: 'chatapp-9da17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXbVQ3QsTBrntFpasSaRUiXSnSIk1MR10',
    appId: '1:1033223278662:ios:ea893d0b34ed85e762ba47',
    messagingSenderId: '1033223278662',
    projectId: 'chatapp-9da17',
    storageBucket: 'chatapp-9da17.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXbVQ3QsTBrntFpasSaRUiXSnSIk1MR10',
    appId: '1:1033223278662:ios:ea893d0b34ed85e762ba47',
    messagingSenderId: '1033223278662',
    projectId: 'chatapp-9da17',
    storageBucket: 'chatapp-9da17.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWwof31d1b1qOXlIBDCjX7ETratJsN82Y',
    appId: '1:1033223278662:web:aab206e39d90231e62ba47',
    messagingSenderId: '1033223278662',
    projectId: 'chatapp-9da17',
    authDomain: 'chatapp-9da17.firebaseapp.com',
    storageBucket: 'chatapp-9da17.firebasestorage.app',
  );
}
